### ISSUE TITLE
KOBAS 3.0 docker image:  unable to open database file

### ISSUE THREAD

**Issue by Artifice120** [fionamcc/Docs#9]
Afternoon,

Thanks for this convenient docker image of KOBAS.

Unfortunately, while running the following command
```
  cd /lustre/isaac/scratch/jtorre28/singularity_containers/

singularity run kobas.sif -a -i /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/braker_aa -s api -o /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/ -t fasta:pro -B /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/

```

I receive the following error.

```
2024-07-12 13:49:00 (668 KB/s) - ‘sqlite3/organism.db.gz’ saved [154417/154417]

Traceback (most recent call last):
  File "/usr/bin/kobas-3.0/scripts/annotate.py", line 3, in <module>
    from kobas.scripts import annotate
  File "/usr/bin/kobas-3.0/src/kobas/scripts/annotate.py", line 99, in <module>
    organismdb = dbutils.KOBASDB(kobasrc['kobasdb'] + 'organism.db')
  File "/usr/bin/kobas-3.0/src/kobas/dbutils.py", line 15, in __init__
    self.con = sqlite3.connect(dbfile)
sqlite3.OperationalError: unable to open database file
Total proteins in pathways: 0
Use of uninitialized value $pathway_ctr in concatenation (.) or string at /usr/bin/create_KOBAS_pathway_tsv.pl line 71.
Total pathways annotated:
Use of uninitialized value $pathway_ctr in division (/) at /usr/bin/create_KOBAS_pathway_tsv.pl line 72.
Illegal division by zero at /usr/bin/create_KOBAS_pathway_tsv.pl line 72.

```

my fasta file of predicted proteins is in this format

```
[jtorre28@login1 BRAKER-arthro-busco]$ head braker.aa
>g298.t1
XIVHLVGRVLPPPPRGADWKRNSDLGGIEGKQYKTKHRKSIPVIRGGQHRPPTTDNRPKA
RCEDPTISPPRFFL*
>g299.t1
MALCPLTSTEVLEFLPLNTWTENLYEGAVLVDVNCNNTKLDNCVNEKQLLESKRVKESIQ
ILQNITENESELINTLELEVILNIELRTGDNSKMTNGLNRVSNNWKSGDHVEFLFGIDVD
NIFVRKIKTYEEFKNVLDQLKGENIEHFKRIEPKINEYVAVYSPLYAGVYRAKVLVQDSK
NKDMIKCALMDFAKVDKIPSKDLFALPDYVSLFKEYDEDDRQFSRQKVVLKDLLSSVSLN
DDIQKLS*
```

and this is the last portion of the stdout

```
Building a new DB, current time: 07/12/2024 15:16:23
New DB name:   /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/seq_pep/api.pep.fasta
New DB title:  seq_pep/api.pep.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 18277 sequences in 0.342103 seconds.
```

Any help is appreciated.

thanks

**Comment by Artifice120** [comment]
My bad,

I just had the directory mounted incorrectly to the container.

correct format
```
cd /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/

singularity run -B /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/:/work-dir /lustre/isaac/scratch/jtorre28/singularity_containers/kobas.sif -a -i /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/braker_aa -s api -o /lustre/isaac/scratch/jtorre28/foxgloves/purged/purged2/BRAKER-arthro-busco/  -t fasta:pro
```
